language: java
jdk: oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - $HOME/.m2

after_success:
  -  mvn -N com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=$TRAVIS_BUILD_DIR/target/coverage-reports/jacoco/jacoco.xml -DprojectToken=884cdc9110044d2e9efd91854ead6c82 -DapiToken=884cdc9110044d2e9efd91854ead6c82
